name: XcodeCloudTestApp
options:
  bundleIdPrefix: com.xcodecloud.mcp
  deploymentTarget:
    iOS: '16.0'
  xcodeVersion: '15.0'
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: '5.9'
    MARKETING_VERSION: '1.0.0'
    CURRENT_PROJECT_VERSION: '1'
    DEVELOPMENT_TEAM: ''
    CODE_SIGN_STYLE: Automatic

targets:
  XcodeCloudTestApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - '**/.DS_Store'
    resources:
      - path: Resources
        excludes:
          - '**/.DS_Store'
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_BUNDLE_IDENTIFIER: com.xcodecloud.mcp.testapp
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: 'UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight'
        INFOPLIST_KEY_CFBundleDisplayName: 'XC Test App'

  XcodeCloudTestAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/UnitTests
        excludes:
          - '**/.DS_Store'
    dependencies:
      - target: XcodeCloudTestApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_BUNDLE_IDENTIFIER: com.xcodecloud.mcp.testapp.tests
        TEST_HOST: '$(BUILT_PRODUCTS_DIR)/XcodeCloudTestApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/XcodeCloudTestApp'
        BUNDLE_LOADER: '$(TEST_HOST)'

  XcodeCloudTestAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/UITests
        excludes:
          - '**/.DS_Store'
    dependencies:
      - target: XcodeCloudTestApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_BUNDLE_IDENTIFIER: com.xcodecloud.mcp.testapp.uitests
        TEST_TARGET_NAME: XcodeCloudTestApp

schemes:
  XcodeCloudTestApp:
    build:
      targets:
        XcodeCloudTestApp: all
        XcodeCloudTestAppTests: [test]
        XcodeCloudTestAppUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: XcodeCloudTestAppTests
          parallelizable: false
          randomExecutionOrder: true
        - name: XcodeCloudTestAppUITests
          parallelizable: false
          randomExecutionOrder: false
      language: en
      region: US
